### ISSUE TITLE
Should this library include helpers and code for initialising the touch screen?

### ISSUE THREAD

**Issue by sumnerboy12** [austinscreations/OXRS-AC-WT32-ESP-LIB#2]
Seems like this would be needed by anything based on the WT32. Not sure how generic that LVGL initialisation code is and whether it can be abstracted out to this library, but worth investigating so downstream firmware doesn't have to duplicate the efforts of the TP32 firmware.

**Comment by austinscreations** [comment]
LVGL initialization is very simple. Not at my computer so can't easily look at lines of code to quote. But also lglvgl is quite a powerful library and as much as it can do someone may not use it (I dunno why) but it might be best left out

**Comment by sumnerboy12** [comment]
I think there is quite a bit of code that could be moved to this library. The TFT and touch pad initialisation, the LGVL initialisation (I don't mind if this lib forces the user to stick with LGVL - it is a good option and means we only have one display driver to support). It could also handle the backlight control (with an API for the f/w to adjust as required).

It would make building another WT32 based device a lot easier having all that stuff squared away. 

@moinmoin-sh - you know this code better than anyone - do you have a view?

**Comment by austinscreations** [comment]
With that reasoning and if your moving a fair bit over then I'd say sure go for.

**Comment by moinmoin-sh** [comment]
I feel happy with how it is. I like to have everything related to the panel in one place with the logical objects in seperate classes. Took me a while to get things sorted and in sequence. Who knows if there will be a different HW this FW could run on and how that could look like. If there will be,  optimisations can be done as required.

**Comment by sumnerboy12** [comment]
Fair enough. 

I was coming at it from the other way, meaning the WT32 library could be used for other firmware based on the WT32 device, so would it be useful to move things like the TFT and touchpad initialization into the lib so other firmware doesn't have to implement it again.

Rather than running the TP32 firmware on different hardware.

I might have a little fiddle and see if things fall out nicely. Will get you to have a look before committing any changes tho.
